services:
  vuelos-app:
    build:
      context: . # Path: docker/
      dockerfile: Dockerfile
    image: planes-scraping:1.0-pw-prod # Name of the image
    container_name: prod-planes-pw
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1 # para mostrar los logs en tiempo real
    env_file:
      - .env
    # file: entrypoint.py
    # instance the flask: app = Flask(__name__) // app = create_app()
    # gunicorn normally is use port 8000
    # command: flask --app main run --host=0.0.0.0 --port=5000 

    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:${PORT:-5000}/status/health'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# networks:
#   default:
#     external: true
#     name: dokploy-network
