services:
  vuelos-app:
    build:
      context: . # Path: docker/
      dockerfile: Dockerfile
    image: vuelos-private-radar:1.1-pro # Name of the image
    container_name: pro-vuelos-private-radar-py-amd64
    restart: always
    environment:
      - ENV_FILE=.env.chrome
    env_file:
      - .env.chrome
      # production env
      # volumes:
      #   - .:/app
      # file: entrypoint.py
      # instance the flask: app = Flask(__name__) // app = create_app()
      # gunicorn normally is use port 8000
    command: [ "gunicorn", "-w", "${WORKERS:-2}", "-b", "0.0.0.0:${PORT:-5000}", "--timeout", "${TIMEOUT:-120}", "main:app" ]
    # command: flask --app main run --host=0.0.0.0 --port=5000 

    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:${PORT:-5000}/status/health'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# networks:
#   default:
#     external: true
#     name: dokploy-network
