services:
  vuelos-app:
    build:
      context: ../ # Path: docker/
      dockerfile: docker/Dockerfile-py
    image: vuelos-private-radar:1.1-pro # Name of the image
    container_name: pro-vuelos-private-radar-py-amd64
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1 # para mostrar los logs en tiempo real
      - ENV_FILE=chrome.env
    env_file:
      - ../chrome.env 
      # production env
    volumes:
      - ../:/app
  # file: entrypoint.py
  # instance the flask: app = Flask(__name__) // app = create_app()
  # gunicorn normally is use port 8000
    command: ["gunicorn", "-w", "3", "-b", "0.0.0.0:5000","--timeout","120","--reload",  "entrypoint:app"]
