# FROM python:3.11.9-slim-bullseye as builder
# Usa una imagen base compatible con ARM
FROM --platform=linux/arm64 python:3.11.9-bullseye

# Establece el directorio de trabajo
WORKDIR /app

# Copia los requisitos al contenedor
COPY ./requirements.txt /app/

# Instala las dependencias de Python
# RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN pip install -r requirements.txt

RUN apt install -y chromium

# install chromedriver, which will be located at /usr/bin/chromedriver
RUN apt-get update -qqy \
    && apt-get -qqy install chromium-driver \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/*

# #... (install dependencies)

# # Create the necessary directories for copying the binary
# RUN mkdir -p /var/chromedriver/

# # copy the chromedriver binary, so that it can be patched by undetected_chromedriver
# ENV CHROMEDRIVER_PATH=/var/chromedriver/chromedriver_copy
# RUN cp /usr/bin/chromedriver ${CHROMEDRIVER_PATH}

# Segunda etapa
# FROM python:3.11.9-slim-bullseye

# WORKDIR /app

# COPY . /app/

# # Copiamos los paquetes instalados de la primera etapa
# COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
# COPY --from=builder /usr/local/bin /usr/local/bin

CMD [ "/bin/sh" ]