services:
  vuelos-app:
    build:
      context: ../ # Path: docker/
      dockerfile: docker/Dockerfile-py-arm
    image: vuelos-private-radar:1.1-arm # Name of the image
    container_name: vuelos-private-radar-arm
    ports:
      - "5000:5000"

    volumes: # poner el path igual qu eel contexto
      - ../:/app
  # file: entrypoint.py
  # instance the flask: app = Flask(__name__) // app = create_app()
  # gunicorn normally is use port 8000
    command: ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "entrypoint:app"]