services:
  vuelos-app:
    build:
      context: ../ # Path: docker/
      dockerfile: docker/Dockerfile-py
    image: vuelos-private-radar:1.1-py # Name of the image
    container_name: dev-vuelos-private-radar-py-amd64
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1 # para mostrar los logs en tiempo real
      - ENV_FILE=chrome.env
    env_file:
      - ../chrome.env 
    volumes:
      - ../:/app
  # file: entrypoint.py
  # instance the flask: app = Flask(__name__) // app = create_app()
    # command: flask run --host=0.0.0.0:5000 --reload
    command: sleep infinity