services:
  app:
    build:
      context: ../ # Path: docker/
      dockerfile: docker/Dockerfile-py
    image: vuelos-private-radar # Name of the image
    container_name: vuelos-private-radar
    ports:
      - "5000:5000"
  # file: entrypoint.py
  # instance the flask: app = Flask(__name__) // app = create_app()
  # gunicorn normally is use port 8000
    command: ["gunicorn", "-b", "0.0.0.0:5000","entrypoint:app"]