services:
  vuelos-app:
    build:
      context: ../ # Path: docker/
      dockerfile: docker/Dockerfile-py-firefox
    image: vuelos-private-radar:1.1-firefox # Name of the image
    container_name: vuelos-private-radar-firefox
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1 # para mostrar los logs en tiempo real
    volumes:
      - ../:/app
  # file: entrypoint.py
  # instance the flask: app = Flask(__name__) // app = create_app()
  # gunicorn normally is use port 8000
    # command: ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "entrypoint:app"]
    # command: gunicorn -w 2 -b 0.0.0.0:5000 --capture-output entrypoint:app
    # command: ["sleep", "infinity"]
    command: flask run --debug --host=0.0.0.0 --port=5000